### ISSUE TITLE
Add a `hostname` to be used as a class member for each configuration

### ISSUE THREAD

**Issue by CherfaElyes** [sentrysoftware/metricshub#218]
# Specification

In our current metricshub.yaml configuration, a host has a `host.name` attribute which is used:
1. as a hostname to send and recieve data through different protocols.
2. as a class member in Prometheus when searching for metrics for a given hostname.

We would like to add a `hostname` which will be used as a class member for each configuration. If this attribute isn't specified, the default metric host name would be the `host.name`.

This will help users to achieve this:
```yaml
       svp-host:
         attributes:
           host.name: svp-host
           host.type: win
         protocols:
           wmi:
             hostname: svp-host
             username user
             password: *******

       vsp-g200:
         attributes:
           host.name: vsp-g200
           host.type: storage
         protocols:
           wbem:
             hostname: svp-host
             username: user
             password: *****
```

Two resources with the same host endpoint (`hostname: svp-host`) can be configured and uniquely identified.

# Milestones
- [x] General setup over the agent and the engine (IConfiguration, NetworkHelper, ConfigHelper).
- [x] Ping Extension.
- [x] SNMP, SNMPv3 & Snmp common Extensions.
- [x] IPMI Extension.
- [x] HTTP Extension.
- [x] WMI & Win common Extensions.
- [x] WinRm Extension.
- [x] OsCommand Extension.
- [x] WBEM Extension.
- [x] Hardware Module.
- [x] Test all the protocols and adjust if required.
