### ISSUE TITLE
Documentation review

### ISSUE THREAD

**Issue by NassimBtk** [sentrysoftware/metricshub#399]
## Tasks

- [x] In `index.md` > `Operating Principle`: update sentence to `OpenTelemetry Collection a production environment`.
- [x] Fix table of content in `debian`, `rhel`, `docker` and `windows` that always points to the first section.
- [x] Update the download link for `install/debian-linux.html`, `install/docker.html`, `install/windows.html`, `install/redhat-linux.html`,   for the `MetricsHub's Web Site` link use `https://metricshub.com/downloads` instead of `https://metricshub.com/`.
- [x] Remove project info reports so that they are not indexed.
- [x] In cli.md, under "Protocol to be used : " add  `WinRM`
